### PR TITLE
20191119 1132

### PR DESCRIPTION
**Pull request by kaylagalway**
New swipe to delete feature added and network timeout notification.
New version of Xcode introduced a good amount of xml changes.
Reviewed this diff with @devinreams

### CODE REVIEW

**Comment by Delphine** [comment]
I'm not sure how the added xml will affect Pontoon.
@Pike: Would you recommend we try it? Or should we avoid and try to remove these instances from the code?

**Comment by Pike** [comment]
My suggestion is to test this on the Pontoon stage, or to file a bug for investigating the branch by the Pontoon team.

There's really little we can do for these xcode changes, other than being reactive when things change.

@kaylagalway , which update of XCode triggers this? This sounds like a recipe for trouble if people use different versions of XCode, too.

**Comment by Delphine** [comment]
I've filed this for investigation: https://bugzilla.mozilla.org/show_bug.cgi?id=1601361
We're blocked on exposing strings for Lockwise iOS until then.

**Comment by Delphine** [comment]
I'm going to merge this because it seems like this works with Pontoon. Thanks!

**Pull request merged**
